### create user

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "firstName": "Otavio",
  "lastName": "Piza",
  "username": "OtavioPiza",
  "email": "otaviopiza27@gmail.com",
  "password": "test"
}

### log user in

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "OtavioPiza",
  "password": "test"
}

### log user in invalid uname

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "NotOtavioPiza",
  "password": "test"
}

### log user in invalid pass

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "OtavioPiza",
  "password": "Nottest"
}

### verify

POST http://localhost:3000/api/auth/verify
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik90YXZpb1BpemEiLCJlbWFpbCI6Im90YXZpb3BpemEyN0BnbWFpbC5jb20iLCJpZCI6IjYxOWU5MWExODI4ODBiMzczZTZhYTYwMiIsImlhdCI6MTYzNzc4OTI3OX0.ib-dZluMxy_5sKNAq1CHIRvlOf8IXsl9SXjA3Cyco2Q

{
  "code": "92022506"
}

### resend ver code

POST http://localhost:3000/api/auth/verify/resend
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik90YXZpb1BpemEiLCJlbWFpbCI6Im90YXZpb3BpemEyN0BnbWFpbC5jb20iLCJpZCI6IjYxOWU5MWExODI4ODBiMzczZTZhYTYwMiIsImlhdCI6MTYzNzc4OTI3OX0.ib-dZluMxy_5sKNAq1CHIRvlOf8IXsl9SXjA3Cyco2Q

### verify

POST http://localhost:3000/api/auth/verify
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik90YXZpb1BpemEiLCJlbWFpbCI6Im90YXZpb3BpemEyN0BnbWFpbC5jb20iLCJpZCI6IjYxOWU5MWExODI4ODBiMzczZTZhYTYwMiIsImlhdCI6MTYzNzc4OTI3OX0.ib-dZluMxy_5sKNAq1CHIRvlOf8IXsl9SXjA3Cyco2Q

{
"code": "11293403"
}