### create user

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "firstName": "Otavio",
  "lastName": "Piza",
  "username": "OtavioPiza",
  "email": "otaviostpiza@gmail.com",
  "password": "test"
}

### log user in

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "OtavioPiza",
  "password": "test"
}

### log user in invalid uname

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "NotOtavioPiza",
  "password": "test"
}

### log user in invalid pass

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "OtavioPiza",
  "password": "Nottest"
}
