POST http://localhost:3001/api/task
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik90YXZpb1BpemEiLCJlbWFpbCI6Im90YXZpb3BpemEyN0BnbWFpbC5jb20iLCJpZCI6IjYxOWU5MWExODI4ODBiMzczZTZhYTYwMiIsImlhdCI6MTYzNzc4OTI3OX0.ib-dZluMxy_5sKNAq1CHIRvlOf8IXsl9SXjA3Cyco2Q

{
  "title": "test"
}

###

DELETE http://localhost:3001/api/task
Content-Type: application/json
#Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik90YXZpb1BpemEiLCJlbWFpbCI6Im90YXZpb3BpemEyN0BnbWFpbC5jb20iLCJpZCI6IjYxOWU5MWExODI4ODBiMzczZTZhYTYwMiIsImlhdCI6MTYzNzc4OTI3OX0.ib-dZluMxy_5sKNAq1CHIRvlOf8IXsl9SXjA3Cyco2Q

{
  "id": "61a41e66218bd4cad6a09b7b"
}

###

DELETE http://localhost:3001/api/task
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im90YXZpby5waXphIiwiZW1haWwiOiJvdGF2aW8ucGl6YUBnb2JyYXNhLm9yZyIsImlkIjoiNjFhMmZlNWFkZTRkNmM4NWI2Mzc1MGU3IiwiaWF0IjoxNjM4MTQ1NTQwfQ.xpWx6SgAZj1ZqDLR3Z3jxRzzdigdOpy-oeniY4_KG3w

{
  "id": "61a41e66218bd4cad6a09b7b"
}

###

DELETE http://localhost:3001/api/task
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik90YXZpb1BpemEiLCJlbWFpbCI6Im90YXZpb3BpemEyN0BnbWFpbC5jb20iLCJpZCI6IjYxOWU5MWExODI4ODBiMzczZTZhYTYwMiIsImlhdCI6MTYzNzc4OTI3OX0.ib-dZluMxy_5sKNAq1CHIRvlOf8IXsl9SXjA3Cyco2Q

{
  "id": "61a41e66218bd4cad6a09b7b"
}